function ph(el){var t=el.getAttribute("data-ph")||"Sagulubbek";var svg="<svg xmlns='http://www.w3.org/2000/svg' width='800' height='450'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0%' stop-color='#0ea5e9'/><stop offset='100%' stop-color='#22d3ee'/></linearGradient></defs><rect width='100%' height='100%' fill='#0f172a'/><circle cx='120' cy='120' r='70' fill='#1dd1a1'/><rect x='112' y='76' width='16' height='60' rx='8' fill='#0f766e'/><path d='M300 180c60-10 120-40 150-80 10 20 10 40 10 60-40 30-90 48-160 48-4-8-4-18 0-28z' fill='url(#g)' opacity='.9'/><text x='60%' y='54%' text-anchor='middle' font-family='Inter, Arial' font-size='42' fill='#e6faff'>"+encodeURIComponent(t)+"</text></svg>";return "data:image/svg+xml;utf8,"+svg}
function gate(){try{if(sessionStorage.getItem("sglb.auth")==="1"){return}var overlay=document.createElement("div");overlay.className="gate";overlay.innerHTML="<div class='gate-card'><h2>Masuk</h2><div class='field'><label>Nama</label><input id='gName' autocomplete='off' placeholder='Nama'></div><div class='field'><label>Sandi</label><input id='gPass' type='password' placeholder='Sandi'></div><div class='gate-actions'><div class='err' id='gErr'></div><button id='gBtn' class='btn'>Masuk</button></div></div>";document.body.appendChild(overlay);var btn=overlay.querySelector("#gBtn");var nameIn=overlay.querySelector("#gName");var passIn=overlay.querySelector("#gPass");function check(){var n=(nameIn.value||"").trim();var p=(passIn.value||"").trim();if(n==="Sagulubbek"&&p==="Sagulubbek"){sessionStorage.setItem("sglb.auth","1");document.body.removeChild(overlay)}else{overlay.querySelector("#gErr").textContent="Nama atau sandi salah"}}btn.addEventListener("click",function(){check()});passIn.addEventListener("keydown",function(e){if(e.key==="Enter"){check()}})}catch(e){}}
function setShareLinks(){try{var url=encodeURIComponent(location.href);var text=encodeURIComponent(document.title);document.querySelectorAll("[data-share-wa]").forEach(function(a){a.href="https://wa.me/?text="+text+"%20"+url});document.querySelectorAll("[data-share-fb]").forEach(function(a){a.href="https://www.facebook.com/sharer/sharer.php?u="+url})}catch(e){}}
function setStandardNav(){try{var nav=document.querySelector("[data-nav]");if(!nav)return;var want=[{t:"Data Mahasiswa",u:"data-mahasiswa.html"},{t:"Foto",u:"foto.html"}];nav.innerHTML="";want.forEach(function(x){var a=document.createElement("a");a.className="nav-link";a.href=x.u;a.textContent=x.t;nav.append(a)})}catch(e){}}
function buildThemeStyles(){try{if(document.getElementById("sglb-theme-style"))return;var css=""
++".theme-light body{background:#f8fafc;color:#0f172a}"
++".theme-light .site-header,.theme-light .site-footer{background:#ffffff;color:#0f172a;border-color:#e2e8f0}"
++".theme-light .nav-link{color:#0f172a}"
++".theme-light .card{background:#ffffff;border-color:#e2e8f0}"
++".theme-light .list-item{background:#ffffff;border-color:#e2e8f0}"
++".theme-light .card-title{color:#0f172a}"
++".theme-light .card-desc{color:#1f2937}"
++".theme-light .article-body,.theme-light .article-body p{color:#0f172a}"
++".theme-light .article .card-desc{color:#111827}"
++".theme-light .btn{color:#0f172a}"
++".theme-dark body{background:#0b1220;color:#e6faff}"
++".theme-dark .site-header,.theme-dark .site-footer{background:#0f172a;color:#e6faff;border-color:#0b1220}"
++".theme-dark .nav-link{color:#e6faff}"
++".theme-dark .card{background:#0f1628;border-color:#0b1220}"
++".theme-dark .list-item{background:#0f1628;border-color:#0b1220}"
++".theme-dark .card-title{color:#e6faff}"
++".theme-dark .card-desc{color:#cbd5e1}"
++".theme-dark .article-body,.theme-dark .article-body p{color:#e6faff}"
++".theme-dark .btn{color:#0f172a}"
;var s=document.createElement("style");s.id="sglb-theme-style";s.textContent=css;document.head.appendChild(s)}catch(e){}}
function applyTheme(t){try{var root=document.documentElement;root.classList.remove("theme-dark","theme-light");root.classList.add(t==="dark"?"theme-dark":"theme-light");localStorage.setItem("sglb.theme",t)}catch(e){}}
function initTheme(){buildThemeStyles();var pref=localStorage.getItem("sglb.theme");if(!pref){pref=window.matchMedia&&window.matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light"}applyTheme(pref)}
function updateThemeToggleIcon(){try{var svg=document.querySelector(".theme-toggle svg");if(!svg)return;var t=localStorage.getItem("sglb.theme")||"light";if(t==="light"){svg.innerHTML="<path d='M12 2c3.866 0 7 3.134 7 7 0 2.24-1.043 4.232-2.676 5.531-.29.231-.464.576-.464.943V17a2 2 0 0 1-2 2h-1v1a2 2 0 1 1-4 0v-1H8a2 2 0 0 1-2-2v-1.526c0-.367-.174-.712-.464-.943A6.997 6.997 0 0 1 5 9c0-3.866 3.134-7 7-7z' fill='#facc15'/><path d='M9 19h6' stroke='#0f172a' stroke-width='2' stroke-linecap='round'/>"}else{svg.innerHTML="<path d='M12 2c3.866 0 7 3.134 7 7 0 2.24-1.043 4.232-2.676 5.531-.29.231-.464.576-.464.943V17a2 2 0 0 1-2 2h-1v1a2 2 0 1 1-4 0v-1H8a2 2 0 0 1-2-2v-1.526c0-.367-.174-.712-.464-.943A6.997 6.997 0 0 1 5 9c0-3.866 3.134-7 7-7z' fill='none' stroke='#e6faff' stroke-width='2'/><path d='M9 19h6' stroke='#e6faff' stroke-width='2' stroke-linecap='round'/>"}}catch(e){}}
function addThemeToggle(){try{var hdr=document.querySelector(".header-inner");if(!hdr||hdr.querySelector(".theme-toggle"))return;var btn=document.createElement("button");btn.className="btn theme-toggle";btn.type="button";btn.setAttribute("aria-label","Ubah tema");btn.title="Ubah tema";btn.style.borderRadius="9999px";btn.style.border="none";btn.style.padding="8px";btn.style.marginLeft="8px";btn.style.background="linear-gradient(135deg,#0ea5e9,#22d3ee)";btn.style.color="#0f172a";btn.style.display="inline-flex";btn.style.alignItems="center";var icon=document.createElementNS("http://www.w3.org/2000/svg","svg");icon.setAttribute("viewBox","0 0 24 24");icon.setAttribute("width","20");icon.setAttribute("height","20");btn.append(icon);btn.addEventListener("click",function(){var cur=localStorage.getItem("sglb.theme")||"light";applyTheme(cur==="dark"?"light":"dark");updateThemeToggleIcon()});var navToggle=document.querySelector(".nav-toggle");if(navToggle&&navToggle.parentNode===hdr){navToggle.insertAdjacentElement("afterend",btn)}else{hdr.appendChild(btn)}updateThemeToggleIcon();if(!document.body.contains(btn)){var fab=document.createElement("button");fab.className="btn theme-toggle";fab.type="button";fab.setAttribute("aria-label","Ubah tema");fab.title="Ubah tema";fab.style.position="fixed";fab.style.right="12px";fab.style.bottom="12px";fab.style.border="none";fab.style.borderRadius="9999px";fab.style.padding="10px";fab.style.background="linear-gradient(135deg,#0ea5e9,#22d3ee)";fab.style.zIndex="9999";var i2=document.createElementNS("http://www.w3.org/2000/svg","svg");i2.setAttribute("viewBox","0 0 24 24");i2.setAttribute("width","22");i2.setAttribute("height","22");fab.append(i2);fab.addEventListener("click",function(){var cur=localStorage.getItem("sglb.theme")||"light";applyTheme(cur==="dark"?"light":"dark");updateThemeToggleIcon()});document.body.appendChild(fab);updateThemeToggleIcon()}}catch(e){}}
function boot(){var nav=document.querySelector("[data-nav]");var toggle=document.querySelector(".nav-toggle");if(toggle&&nav){toggle.setAttribute("aria-controls","site-nav-menu");nav.id=nav.id||"site-nav-menu";if(!toggle.querySelector(".bar")){toggle.classList.add("hamb");toggle.innerHTML="<span class='bar'></span><span class='bar'></span><span class='bar'></span>"}function s(i){if(toggle.querySelector(".bar"))return}var isMStart=window.matchMedia("(max-width: 840px)").matches;if(isMStart){nav.setAttribute("data-open","true");toggle.setAttribute("aria-expanded","true")}toggle.addEventListener("click",function(){var o=nav.getAttribute("data-open")==="true";nav.setAttribute("data-open",String(!o));toggle.setAttribute("aria-expanded",String(!o))});document.addEventListener("click",function(e){var isM=window.matchMedia("(max-width: 840px)").matches;var o=nav.getAttribute("data-open")==="true";if(!isM||!o)return;var inside=nav.contains(e.target)||toggle.contains(e.target);if(!inside){nav.removeAttribute("data-open");toggle.setAttribute("aria-expanded","false")}});document.addEventListener("keydown",function(e){if(e.key==="Escape"){nav.removeAttribute("data-open");toggle.setAttribute("aria-expanded","false")}});document.querySelectorAll(".site-nav a").forEach(function(a){a.addEventListener("click",function(){nav.removeAttribute("data-open");toggle.setAttribute("aria-expanded","false")})})}var y=document.getElementById("year");if(y)y.textContent=String(new Date().getFullYear());var fg=document.querySelector(".site-footer .footer-grid");if(fg&&!fg.querySelector(".footer-col h3:nth-child(1)+ul a[href*='visi-misi.html']")){var col=document.createElement("div");col.className="footer-col";var h=document.createElement("h3");h.textContent="Tentang";var ul=document.createElement("ul");ul.className="footer-nav";[{t:"Visi & Misi",u:"visi-misi.html"},{t:"Tugas & Fungsi",u:"tugas-fungsi.html"},{t:"Sejarah",u:"sejarah.html"},{t:"Lambang",u:"lambang.html"},{t:"Daftar Kontak",u:"daftar-kontak.html"},{t:"Kontak Kami",u:"kontak-kami.html"},{t:"Galeri Video",u:"galeri-video.html"},{t:"Pendidikan",u:"pendidikan.html"}].forEach(function(x){var li=document.createElement("li");var a=document.createElement("a");a.href=x.u;a.textContent=x.t;li.append(a);ul.append(li)});col.append(h,ul);fg.append(col)}document.querySelectorAll("img[data-ph]").forEach(function(img){img.src=ph(img)});var lb=document.getElementById("lightbox");if(lb){document.querySelectorAll("[data-close]").forEach(function(x){x.addEventListener("click",function(){lb.removeAttribute("data-open");lb.setAttribute("aria-hidden","true")})})}setShareLinks();gate()}document.addEventListener("DOMContentLoaded",function(){setStandardNav();initTheme();addThemeToggle();boot()});
